Feature/backend distribution/service service business
itskikat/tqs_project pull request #75
Opened 2021-06-09 17:09 UTC by itskikat

2021-06-09 17:14 UTC, itskikat commented
Please do ignore this, as I forgot something!! I'll be adding in a few minutes!

2021-06-09 17:41 UTC, itskikat commented
I do believe it's ok now! I'm sorry for the hassle!

2021-06-10 13:55 UTC, margaridasmartins requested changes
Great work!

Just one small issue, instead of throwing exception deleting a business service in ServiceService could return a boolean stating if the service exists or not. This can give a better error message in the business controller

2021-06-10 13:56 UTC, margaridasmartins approved these changes

2021-06-10 13:57 UTC, merged